CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_MOUSE=y

CONFIG_PMW3610_ACONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_ZMK_USB_LOGGING=y

CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=yLT_INIT_POWER_UP_EXTRA_DELAY_MS=1000
